### ISSUE TITLE
🐛 Bug: comments are removed on prettier run

### ISSUE THREAD

**Issue by HolgerJeromin** [JoshuaKGoldberg/prettier-plugin-curly#179]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

"prettier-plugin-curly": "0.1.3":

This code...
```ts
if(document.body)
  //Important comment which will be lost!
  document.body.append('')
```
should be transformed to
```ts
if(document.body) {
  //Important comment which will be lost!
  document.body.append('')
}
```

### Actual

I get
```ts
if(document.body) {
  document.body.append('')
}
```

### Additional Info

Same with block comments: `/* comment */`

**Comment by JoshuaKGoldberg** [comment]
I took a look at this and it's actually pretty hard to do properly 😬. Keeping the comments is doable by checking `node.leadingComments` and `node.trailingComments`. But preserving spacing, especially newlines, is not super easy.

Is there a standard utility package that can be used outside of `@babel/traverse` to print strings? IMO that would be the right solution here.

**Comment by JoshuaKGoldberg** [comment]
Turns out `@babel/generator` works well-ish enough for this (I think). It would be nice to have a Prettier API. #309 has a bit more details & links.
