### ISSUE TITLE
🐛 Bug: cannot parse code includes syntax errors

### ISSUE THREAD

**Issue by so1ve** [JoshuaKGoldberg/prettier-plugin-curly#6]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Should parse and format

```ts
const a =1
const a=1
```

### Actual

Cannot parse and breaks formatting

### Additional Info

We should use prettier's parser. import from `prettier/parser-babel`

PR later

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @so1ve  for bug
