### ISSUE TITLE
🐛 Bug: Remove "bin" from package.json

### ISSUE THREAD

**Issue by navin-moorthy** [JoshuaKGoldberg/prettier-plugin-curly#7]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/prettier-plugin-curly/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

No error in console when installing packages including this package.

### Actual

<img width="1425" alt="image" src="https://github.com/JoshuaKGoldberg/prettier-plugin-curly/assets/39694575/979361d3-e124-48c5-8f20-eafe83bdf564">

### Additional Info

Remove this line -
https://github.com/JoshuaKGoldberg/prettier-plugin-curly/blob/1c2616fa74762e55d3f95fb998804891d5f176ea/package.json#L15

**Comment by JoshuaKGoldberg** [comment]
@allcontributors add @navin-moorthy for bug
